import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { dbConnect } from '@/utils/db'
import HeaderMenu from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Lägg till denna för att slippa skriva   await dbConnect(); i filerna
  const connectToDatabase = async () => {

    try {
      await dbConnect();
      console.log("Connected to the database");
    }catch (error){
      console.error("Error connecting to the database: " + error)
    }
  }
  connectToDatabase();



   // Lägger till HeaderMenu och Footer så finnns de på alla sidor
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderMenu/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
